### ISSUE TITLE
Error in plotting of Fig 3 in your submission to ReScience

### ISSUE THREAD

**Issue by rajeshrinet** [CoraliePicoche/brownian_bug_fluid#1]
@CoraliePicoche I have been having issues with plotting the Figure 3. I get the error:

>   cannot open file '../simulation/pcf_dpow0p25_area10_tmax1000_N200000_U0p0.txt': No such file or directory

Please can you check and let me know if I am missing something?

PS: I could generate all other figures and execute all the code.

**Comment by CoraliePicoche** [comment]
Hello @rajeshrinet ,

No, you are not missing anything, I just need to make the code clearer.

All files "pcf_dpow0p25_area10_tmax1000_N200000_U*' can be generated by the same code, i.e. main_Fig3.cpp. However, as for now, this code only performs one simulation with one value of Utot per run. You have to change  the value of Utot (l.156) to either 0, 0.1, 0.5 or 2.5, and change the name of the files f0 (l.168) and f1 (l.170) to the corresponding extension (_U0p0 ; _U0p1 ; _U0p5 or _U2p5, respectively) to simulate the 4 situations and obtain the 4 files used in pcf_Fig3.r. 
Do not hesitate to tell me if something is unclear.

I will try and explain that better in the comments of the file, thank you for telling me. 

Best regards
Coralie Picoche

**Comment by rajeshrinet** [comment]
Thanks @CoraliePicoche for this quick response.

**Comment by rajeshrinet** [comment]
@CoraliePicoche please consider adding a tests folder in your updates. You can add scripts like one [here](https://github.com/rajeshrinet/brownian_bug_fluid/blob/main/code/tests/fig1.sh) for each of the figures. This would be useful for a new user. You may also choose default parameters for system sizes and time duration such that the code runs quickly. 

You can also supply actual parameters used in the paper

**Comment by CoraliePicoche** [comment]
Thank you very much for the idea and the example you adapted to our case.

I am not sure about your last sentence: do you suggest to have either (or both?) a script for a small system so that new users can have a quick idea of how the program works, or to keep the actual parameters? Or do you, more simply, suggest to have a separate file providing the actual values so that users can modify the small-system script with values used in the paper? I am ok with both, I am just wondering if that is what you meant.

**Comment by rajeshrinet** [comment]
@CoraliePicoche I suggest having both. I do indeed want the users to quickly see how program works and also reproduce the plots in your article. Unfortunately, I do not use c++ regularly, so I do not know what is the best way to do this. So my comment was a bit vague.

A simple way would be to have parameters in two text files. One for quick check and other for actual plots in the article. You can indicate to user both with appropriate warnings. Also give by default the parameters which run quickly in the test folder. This will be useful for any contributors the repo (and you to manage merge requests). They can quickly check if the code runs fine for a smaller system size before pushing changes to the GitHub repo.

**Comment by CoraliePicoche** [comment]
@rajeshrinet  Ok, thank you very much for your answer, this is indeed a very good suggestion.
